---
version: "3.5"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    #ports:
    #  - 9999:9999

  frontend:
    build: .
    environment:
      SRV_API_IP: backend
      SRV_API_PORT: 9999
    ports:
      - 80:80
      - 443:443
    

